### ISSUE TITLE
Implement additional ACL for wiki write permissions

### ISSUE THREAD

**Issue by anaqreon** [anaqreon/hubzilla#15]
Currently only the wiki owner can edit a wiki. Implement a data structure that provides an additional permission group for editors, which may be a subset of the read-only viewers.

**Comment by friendica** [comment]
I might suggest using the write_pages permission as a workable solution for the short term. Long term we need to make the permissions system a bit more extensible.

**Comment by anaqreon** [comment]
I had originally planned to do exactly this, so I have some checks for "write_pages" permissions in the code already; the downside to this is that if you want Bob to be able to read Wiki1 and Wiki2, but you only want him to have write permissions on Wiki2, you're out of luck. For the first iteration this limitation might be acceptable, but it also wouldn't be hard to add another ACL for write permissions using the set_iconfig() function. Or am I missing some subtlety about this additional ACL?

**Comment by anaqreon** [comment]
Is the extensible permissions framework complete enough now to try using it for this purpose?
